### ISSUE TITLE
can you tell me exactly how to improve the accuracy

### ISSUE THREAD

**Issue by cervineee** [LanglandsLin/ActCLR#5]
Hello, using the Data in Data Preparation and the steps in Unsupervised Pre-Training, the ActCLR-joint was less than 86.7% accurate using EPOCH350 in work. PT as a weight, can you tell me exactly how to improve the accuracy

**Comment by cervineee** [comment]
I'm sorry to disturb you, I use the pre-training results are only a little more than 77% , is there any way to improve it

**Comment by cervineee** [comment]
The following issues arise during the evaluation：
Traceback (most recent call last):
  File "main.py", line 67, in <module>
    p.start(int(os.environ["LOCAL_RANK"]))
  File "/home/wangtingwei/ch/ActCLR-main/processor/processor.py", line 234, in start
    self.train(epoch + 1)
  File "/home/wangtingwei/ch/ActCLR-main/processor/linear_evaluation.py", line 146, in train
    loss = self.loss(output, label)
  File "/usr/local/anaconda3/envs/HD/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/anaconda3/envs/HD/lib/python3.8/site-packages/torch/nn/modules/loss.py", line 1174, in forward
    return F.cross_entropy(input, target, weight=self.weight,
  File "/usr/local/anaconda3/envs/HD/lib/python3.8/site-packages/torch/nn/functional.py", line 3029, in cross_entropy
    return torch._C._nn.cross_entropy_loss(input, target, weight, _Reduction.get_enum(reduction), ignore_index, label_smoothing)
TypeError: cross_entropy_loss(): argument 'input' (position 1) must be Tensor, not list
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 3105232) of binary: /usr/local/anaconda3/envs/HD/bin/python
Traceback (most recent call last):
  File "/usr/local/anaconda3/envs/HD/bin/torchrun", line 33, in <module>
    sys.exit(load_entry_point('torch==2.0.1', 'console_scripts', 'torchrun')())
  File "/usr/local/anaconda3/envs/HD/lib/python3.8/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/usr/local/anaconda3/envs/HD/lib/python3.8/site-packages/torch/distributed/run.py", line 794, in main
    run(args)
  File "/usr/local/anaconda3/envs/HD/lib/python3.8/site-packages/torch/distributed/run.py", line 785, in run
    elastic_launch(
  File "/usr/local/anaconda3/envs/HD/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/usr/local/anaconda3/envs/HD/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 250, in launch_agent
    raise ChildFailedError(
